<template>
  <scroll class="Ccontents" :key="2">
    <div>购物车1</div>
    <div>购物车2</div>
    <div>购物车3</div>
    <div>购物车4</div>
    <div>购物车5</div>
    <div>购物车6</div>
    <div>购物车7</div>
    <div>购物车8</div>
    <div>购物车9</div>
    <div>购物车10</div>
    <div>购物车11</div>
    <div>购物车12</div>
    <div>购物车13</div>
    <div>购物车14</div>
    <div>购物车15</div>
    <div>购物车16</div>
    <div>购物车17</div>
    <div>购物车18</div>
    <div>购物车19</div>
    <div>购物车20</div>
    <div>购物车21</div>
    <div>购物车22</div>
    <div>购物车23</div>
    <div>购物车24</div>
    <div>购物车25</div>
    <div>购物车26</div>
    <div>购物车27</div>
    <div>购物车28</div>
    <div>购物车29</div>
    <div>购物车30</div>
    <div>购物车31</div>
    <div>购物车32</div>
    <div>购物车33</div>
    <div>购物车34</div>
    <div>购物车35</div>
    <div>购物车36</div>
    <div>购物车37</div>
    <div>购物车38</div>
    <div>购物车39</div>
    <div>购物车40</div>
    <div>购物车41</div>
    <div>购物车42</div>
    <div>购物车43</div>
    <div>购物车44</div>
    <div>购物车45</div>
    <div>购物车46</div>
    <div>购物车47</div>
    <div>购物车48</div>
    <div>购物车49</div>
    <div>购物车50</div>
    <div>购物车51</div>
    <div>购物车52</div>
    <div>购物车53</div>
    <div>购物车54</div>
    <div>购物车55</div>
    <div>购物车56</div>
    <div>购物车57</div>
    <div>购物车58</div>
    <div>购物车59</div>
    <div>购物车60</div>
    <div>购物车61</div>
    <div>购物车62</div>
    <div>购物车63</div>
    <div>购物车64</div>
    <div>购物车65</div>
    <div>购物车66</div>
    <div>购物车67</div>
    <div>购物车68</div>
    <div>购物车69</div>
    <div>购物车70</div>
    <div>购物车71</div>
    <div>购物车72</div>
    <div>购物车73</div>
    <div>购物车74</div>
    <div>购物车75</div>
    <div>购物车76</div>
    <div>购物车77</div>
    <div>购物车78</div>
    <div>购物车79</div>
    <div>购物车80</div>
    <div>购物车81</div>
    <div>购物车82</div>
    <div>购物车83</div>
    <div>购物车84</div>
    <div>购物车85</div>
    <div>购物车86</div>
    <div>购物车87</div>
    <div>购物车88</div>
    <div>购物车89</div>
    <div>购物车90</div>
    <div>购物车91</div>
    <div>购物车92</div>
    <div>购物车93</div>
    <div>购物车94</div>
    <div>购物车95</div>
    <div>购物车96</div>
    <div>购物车97</div>
    <div>购物车98</div>
    <div>购物车99</div>
    <div>购物车100</div>
  </scroll>
</template>

<script>
import Scroll from "../../components/common/scroll/Scroll.vue";

export default {
  components: { Scroll },
};
</script>

<style scope>
.Ccontents {
  height: 400px;
  overflow: hidden;
}
</style>
